# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AracListe.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CarList_Widget(object):
    def setupUi(self, CarList_Widget):
        CarList_Widget.setObjectName("CarList_Widget")
        CarList_Widget.resize(1177, 837)
        self.tableWidget = QtWidgets.QTableWidget(CarList_Widget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 11, 1051, 451))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)

        self.retranslateUi(CarList_Widget)
        QtCore.QMetaObject.connectSlotsByName(CarList_Widget)

    def retranslateUi(self, CarList_Widget):
        _translate = QtCore.QCoreApplication.translate
        CarList_Widget.setWindowTitle(_translate("CarList_Widget", "Araç Listesi"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("CarList_Widget", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("CarList_Widget", "İlan Numarası"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("CarList_Widget", "Marka/Model"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("CarList_Widget", "Km"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("CarList_Widget", "Yıl"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("CarList_Widget", "Boyalı Parça Sayısı"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("CarList_Widget", "Değişen Parça Sayısı"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("CarList_Widget", "Araç Skoru"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CarList_Widget = QtWidgets.QWidget()
    ui = Ui_CarList_Widget()
    ui.setupUi(CarList_Widget)
    CarList_Widget.show()
    sys.exit(app.exec_())
