# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(188, 193)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LogIn_GroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.LogIn_GroupBox.setGeometry(QtCore.QRect(10, 20, 141, 111))
        self.LogIn_GroupBox.setObjectName("LogIn_GroupBox")
        self.widget = QtWidgets.QWidget(self.LogIn_GroupBox)
        self.widget.setGeometry(QtCore.QRect(0, 20, 139, 84))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.NameInfo_Text = QtWidgets.QLabel(self.widget)
        self.NameInfo_Text.setAlignment(QtCore.Qt.AlignCenter)
        self.NameInfo_Text.setObjectName("NameInfo_Text")
        self.gridLayout.addWidget(self.NameInfo_Text, 0, 0, 1, 1)
        self.name_LineEdit = QtWidgets.QLineEdit(self.widget)
        self.name_LineEdit.setObjectName("name_LineEdit")
        self.gridLayout.addWidget(self.name_LineEdit, 1, 0, 1, 1)
        self.logIn_PushButton = QtWidgets.QPushButton(self.widget)
        self.logIn_PushButton.setObjectName("logIn_PushButton")
        self.gridLayout.addWidget(self.logIn_PushButton, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 188, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LogIn_GroupBox.setTitle(_translate("MainWindow", "Giriş"))
        self.NameInfo_Text.setText(_translate("MainWindow", "İsminizi Giriniz"))
        self.logIn_PushButton.setText(_translate("MainWindow", "Giriş"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
